apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default  
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
      - name: spring-boot-app
        image: steveyang128/ultimate-cicd:23
        ports:
        - containerPort: 8080
